# Generated by Django 4.2.3 on 2023-07-18 21:13

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.CharField(default='5\'9\\"', max_length=10, validators=[api.validators.heightValidator]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pfp',
            field=models.ImageField(blank=True, null=True, upload_to='profilePictures'),
        ),
    ]
